
spring:
  profiles:
    active:
    - dev:

---
server: 
  port: 8201
  param: 123
  
spring:
  profiles: dev
  application:
    name:  microservicecloud-config
eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
server: 
  port: 8202
  param: 456
  
spring:
  profiles: test
  application:
    name:  microservicecloud-config
eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
